### ISSUE TITLE
Stylesheet.allClasses is unreliable

### ISSUE THREAD

**Issue by scf37** [lihaoyi/scalatags#147] opened 2016-11-26 09:21 UTC
Depending on context, it can return empty collection.

Expected output:
```
1
1
```
Actual output:
```
1
0
```

Environment:
```
Scala 2.12.0
Oracle JDK 1.8.0_101
"com.lihaoyi" %% "scalatags" % "0.6.2"
```
Code to reproduce:
```scala
import scalatags.Text.all._
import scalatags.stylesheet.StyleSheet

object STags {
  def main(args: Array[String]): Unit = {

    println(TestCss.allClasses.length)
    foo(TestCss)
  }

  def foo(c: StyleSheet): Unit = {
    println(c.allClasses.length)
  }
}

object TestCss extends StyleSheet {

  val body = cls(
    backgroundColor := "red",
    height := 125,
    &.hover(
      backgroundColor := "blue"
    )
  )
}
```

**Comment by lihaoyi** [comment] 2016-11-26 12:36
I have bumped into this too. The root cause in my case seems to be incremental compilation being unreliable, and wouldn't be surprised if other things could cause it too

**Comment by chipsenkbeil** [comment] 2017-01-04 01:35
I think that I am hitting this as well.

```
package org.scaladebugger.docs.styles

import scalatags.Text.all._
import scalatags.stylesheet._

/**
 * Contains stylesheet implicits.
 */
object Implicits {
  implicit class StyleSheetWrapper(private val styleSheet: StyleSheet) {
    /**
     * Transforms the stylesheet into a <style> tag.
     *
     * @return The style tag representing this stylesheet
     */
    def toStyleTag: Modifier = {
      val styleText = styleSheet.styleSheetText
      println("STYLE TEXT: " + styleText) // Returns empty string
      println("CLASSES: " + styleSheet.allClasses.map(_.name)) // Returns empty seq
      tag("style")(styleText)
    }
  }

  implicit class StringWrapper(private val string: String) {
    /**
     * Transforms the string into into a <style> tag.
     *
     * @return The style tag containing the raw text
     */
    def toStyleTag: Modifier = tag("style")(string)
  }
}
```

**Comment by lihaoyi** [comment] 2017-01-30 09:58
So here's the problem: `.styleSheetText` relies on a macro in order to discover the `val foo: Cls` definitions within the body of the `StyleSheet`, as runtime reflection cannot be used in Scala.js. Unfortunately, when you are treating them as a `styleSheet: StyleSheet`, all those `val foo: Cls` declarations are not visible, and thus `.styleSheetText` returns nothing.

The immediate solution is to call `.styleSheetText` directly on the specific `StyleSheet` object, and not after it's been typed as generic `StyleSheet`. A separate fix would be to ensure every stylesheet has a `val myStyleSheetText: String = styleSheetText` defined within it, so the macro sees the "full" type of the `StyleSheet`, and then externally refer to it via `myStyleSheetText`.

This can already be done, but we should probably enforce it by making `.styleSheetText` `protected` so you are forced to call it within your class.

This would also solve the problems with incremental compilation not working properly when accessing `.styleSheetText` in a separate file.

**Comment by chipsenkbeil** [comment] 2017-01-30 14:21
@lihaoyi any way to prevent the error is a good way to me. Documenting what you just described in this issue also seems like a good idea.

**Comment by lihaoyi** [comment] 2017-02-04 16:10
Fixed by d68682e9264b7e1bd394360c137532b2c83b5fdd

**Closed by lihaoyi** 2017-02-04 16:10 UTC

**Comment by lihaoyi** [comment] 2017-02-04 16:59
See the new `initStyleSheet()` syntax in http://www.lihaoyi.com/scalatags/#CSSStylesheets, which introduces a bit of boilerplate but should avoid this problem entirely

**Comment by chipsenkbeil** [comment] 2017-02-04 17:14
Excellent! I'll grab the new release and try it out when I have some time.
